### PR TITLE
Add virtual destructor to LogCb (#8)

### PR DESCRIPTION
**Pull request by lukejackson**
Addresses #8

### CODE REVIEW

**Comment by lukejackson** [comment]
[clabot:check]

**Comment by lukejackson** [comment]
@edenhill is this project still being maintained by Confluent? I'd like to know whether it is worth raising PRs or forking and maintaining our own version of this code. Thanks

**Comment by edenhill** [comment]
@lukejackson It is, sorry for the slow response to these issues, we've been in the middle of a larger release, but we're back on track now.
Please do file PRs :)

**Comment by lukejackson** [comment]
Thanks @edenhill. Good to know - we are happy to contribute further to this library going forward.

**Pull request merged**
